unbind r
bind r source-file ~/.config/tmux/tmux.conf
#make <leader-r> reload this file

# Set Esc timeout to lower level ( fromm 1000 ms to 10 ms ) 
set -sg escape-time 10

#change leader
set -g prefix M-x #(ALT-x)

# turn mouse on so we can resize panes with the mouse
set -g mouse on

# Set status bar position on top
set-option -g status-position top

#bind vim style pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#bind vims tile split keys
bind-key          | split-window -h
bind-key          \\ split-window -v

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# make the window names stick out of focus
set-option -g allow-rename off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # mocha, latte, frappe, macchiato or mocha
set -ogq @catppuccin_window_status_style 'slanted' 

#CATPPUCCIN config
set -ogq @catppuccin_window_middle_separator ""
set -ogq @catppuccin_status_left_separator "" 
# set -g @catppuccin_window_current_text "#W"
# set -ogq @catppuccin_directory_text "#{pane_current_path}"

set -g @catppuccin-tmux_show_git 1
# Make the status line more pleasant.
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}#{E:@catppuccin_status_session}"

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set -g @plugin 'christoomey/vim-tmux-navigator'

# TPM is the plugin manager that automatically downloads plugins 
# to the plugins folder that tmux sources on loading
# to install first time run 'git clone https://github.com/tmux-plugins/tpm plugins/tpm' in your tmux config dir...
# To install the plugins run leader-I

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm' 
